"""empty message

Revision ID: 13a9bcd9bdce
Revises: 00d15bc0c357
Create Date: 2021-08-19 02:47:08.628540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a9bcd9bdce'
down_revision = '00d15bc0c357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.String(length=255), nullable=True))
        batch_op.create_index(batch_op.f('ix_offices_date'), ['date'], unique=False)

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_personal_id'), ['id'])
        batch_op.create_unique_constraint(batch_op.f('uq_personal_username'), ['username'])

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_records_office_offices', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_records_office_offices', 'offices', ['office'], ['id'])

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_personal_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_personal_id'), type_='unique')

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offices_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
