"""empty message

Revision ID: 1405b6ea71d8
Revises: 3a5786d7fc70
Create Date: 2021-07-11 19:47:49.002473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1405b6ea71d8'
down_revision = '3a5786d7fc70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('office', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedules', 'office')
    # ### end Alembic commands ###
