"""empty message

Revision ID: 1a0c8eefcb44
Revises: 856ce4f8ba31
Create Date: 2021-07-07 01:15:22.429783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a0c8eefcb44'
down_revision = '856ce4f8ba31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('doctor_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('records', 'doctor_id')
    # ### end Alembic commands ###
