"""empty message

Revision ID: 1b544bbe0145
Revises: 1dc755398a6c
Create Date: 2021-07-09 02:10:59.805093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b544bbe0145'
down_revision = '1dc755398a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('pacient_role', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'pacient_role')
    # ### end Alembic commands ###
