"""empty message

Revision ID: 1dc755398a6c
Revises: 1a0c8eefcb44
Create Date: 2021-07-08 00:04:30.068723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dc755398a6c'
down_revision = '1a0c8eefcb44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pregnants')
    op.drop_table('childs')
    op.add_column('patients', sa.Column('estimated_birthday', sa.String(length=255), nullable=True))
    op.add_column('patients', sa.Column('num_fetus', sa.Integer(), nullable=True))
    op.add_column('patients', sa.Column('lr_status', sa.String(length=255), nullable=True))
    op.drop_column('patients', 'pacient_record')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('pacient_record', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('patients', 'lr_status')
    op.drop_column('patients', 'num_fetus')
    op.drop_column('patients', 'estimated_birthday')
    op.create_table('childs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('birthday', sa.VARCHAR(length=50), nullable=True),
    sa.Column('lr_status', sa.VARCHAR(length=255), nullable=True),
    sa.Column('phone4', sa.VARCHAR(length=255), nullable=True),
    sa.Column('refer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pacient_record', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_f_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_l_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_surname', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('trust_factor', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnants',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=20), nullable=True),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=True),
    sa.Column('refer', sa.VARCHAR(length=255), nullable=True),
    sa.Column('pacient_record', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.VARCHAR(length=255), nullable=True),
    sa.Column('address', sa.VARCHAR(length=255), nullable=True),
    sa.Column('trust_factor', sa.BOOLEAN(), nullable=True),
    sa.Column('birthday', sa.VARCHAR(length=50), nullable=True),
    sa.Column('estimated_birthday', sa.VARCHAR(length=255), nullable=True),
    sa.Column('num_fetus', sa.INTEGER(), nullable=True),
    sa.Column('phone5', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
