"""empty message

Revision ID: 3a7bb04449c6
Revises: c9b05f93b1a2
Create Date: 2021-07-11 01:01:59.503593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7bb04449c6'
down_revision = 'c9b05f93b1a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('pacient_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patients', sa.Column('speed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'speed')
    op.drop_table('alert_list')
    # ### end Alembic commands ###
