"""empty message

Revision ID: 3ae1cbdcc06b
Revises: b49981c4d30b
Create Date: 2021-07-22 01:05:12.571189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ae1cbdcc06b'
down_revision = 'b49981c4d30b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('comment', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'comment')
    # ### end Alembic commands ###
