"""users table

Revision ID: 485185fccea8
Revises: 
Create Date: 2021-07-04 18:46:41.174869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '485185fccea8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone2', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.String(length=50), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isDev', sa.Boolean(), nullable=True),
    sa.Column('coment', sa.String(length=255), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=True),
    sa.Column('phone3', sa.String(length=255), nullable=True),
    sa.Column('refer', sa.String(length=255), nullable=True),
    sa.Column('pacient_record', sa.String(length=255), nullable=True),
    sa.Column('lr_f_name', sa.String(length=255), nullable=True),
    sa.Column('lr_l_name', sa.String(length=255), nullable=True),
    sa.Column('lr_surname', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('trust_factor', sa.Boolean(), nullable=True),
    sa.Column('lr_status', sa.String(length=255), nullable=True),
    sa.Column('phone4', sa.String(length=255), nullable=True),
    sa.Column('estimated_birthday', sa.String(length=255), nullable=True),
    sa.Column('num_fetus', sa.Integer(), nullable=True),
    sa.Column('phone5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_reg_time'), 'users', ['reg_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reg_time'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
