"""empty message

Revision ID: 5bb42056eab7
Revises: a1de9b16047b
Create Date: 2021-08-21 04:41:16.989858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb42056eab7'
down_revision = 'a1de9b16047b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.drop_index('ix_offices_date')
        batch_op.drop_column('date')

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('office')

    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('patient_phone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('patient_phone')

    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('offices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.VARCHAR(length=255), nullable=True))
        batch_op.create_index('ix_offices_date', ['date'], unique=False)

    # ### end Alembic commands ###
