"""empty message

Revision ID: 7afeb9f89de6
Revises: b04dc54f5599
Create Date: 2021-08-22 01:35:03.786107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7afeb9f89de6'
down_revision = 'b04dc54f5599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_records_is_interview'), ['is_interview'], unique=False)
        batch_op.create_index(batch_op.f('ix_records_is_send'), ['is_send'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_records_is_send'))
        batch_op.drop_index(batch_op.f('ix_records_is_interview'))

    # ### end Alembic commands ###
