"""empty message

Revision ID: 8167dac94d61
Revises: d9ae10a825da
Create Date: 2021-07-16 22:25:50.655050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8167dac94d61'
down_revision = 'd9ae10a825da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('patients', sa.Column('phone2', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'phone2')
    op.drop_column('patients', 'phone')
    # ### end Alembic commands ###
