"""empty message

Revision ID: 856ce4f8ba31
Revises: 
Create Date: 2021-07-06 02:10:08.148919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '856ce4f8ba31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('childs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('lr_status', sa.String(length=255), nullable=True),
    sa.Column('phone4', sa.String(length=255), nullable=True),
    sa.Column('refer', sa.String(length=255), nullable=True),
    sa.Column('pacient_record', sa.String(length=255), nullable=True),
    sa.Column('lr_f_name', sa.String(length=255), nullable=True),
    sa.Column('lr_l_name', sa.String(length=255), nullable=True),
    sa.Column('lr_surname', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('trust_factor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('refer', sa.String(length=255), nullable=True),
    sa.Column('pacient_record', sa.String(length=255), nullable=True),
    sa.Column('lr_f_name', sa.String(length=255), nullable=True),
    sa.Column('lr_l_name', sa.String(length=255), nullable=True),
    sa.Column('lr_surname', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('trust_factor', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('refer', sa.String(length=255), nullable=True),
    sa.Column('pacient_record', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_serial', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_num', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_date', sa.String(length=255), nullable=True),
    sa.Column('lr_pass_issued', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('trust_factor', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('estimated_birthday', sa.String(length=255), nullable=True),
    sa.Column('num_fetus', sa.Integer(), nullable=True),
    sa.Column('phone5', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doctor', sa.String(length=255), nullable=True),
    sa.Column('pacient', sa.String(length=255), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('trust', sa.Boolean(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_records_date'), 'records', ['date'], unique=False)
    op.create_index(op.f('ix_records_time'), 'records', ['time'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('surname', sa.String(length=20), nullable=True),
    sa.Column('sex', sa.Boolean(), nullable=True),
    sa.Column('birthday', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone2', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('reg_time', sa.DateTime(), nullable=True),
    sa.Column('isActive', sa.String(length=50), nullable=True),
    sa.Column('isAdmin', sa.Boolean(), nullable=True),
    sa.Column('isDev', sa.Boolean(), nullable=True),
    sa.Column('division', sa.String(length=255), nullable=True),
    sa.Column('certificate', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.Column('coment', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_reg_time'), 'users', ['reg_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reg_time'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_records_time'), table_name='records')
    op.drop_index(op.f('ix_records_date'), table_name='records')
    op.drop_table('records')
    op.drop_table('pregnants')
    op.drop_table('patients')
    op.drop_table('childs')
    # ### end Alembic commands ###
