"""empty message

Revision ID: 9f0d788341de
Revises: 13a9bcd9bdce
Create Date: 2021-08-19 06:33:30.027771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0d788341de'
down_revision = '13a9bcd9bdce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('office', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personal', schema=None) as batch_op:
        batch_op.drop_column('office')

    # ### end Alembic commands ###
