"""empty message

Revision ID: a7c16d5ac796
Revises: 8167dac94d61
Create Date: 2021-07-18 03:35:57.621154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c16d5ac796'
down_revision = '8167dac94d61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('full_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'full_name')
    # ### end Alembic commands ###
