"""empty message

Revision ID: ab63e1372365
Revises: 1b544bbe0145
Create Date: 2021-07-09 23:45:00.228395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab63e1372365'
down_revision = '1b544bbe0145'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('reception', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'reception')
    # ### end Alembic commands ###
