"""empty message

Revision ID: ac57c1b881fa
Revises: d8f05ff5b716
Create Date: 2021-08-24 12:40:48.616538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac57c1b881fa'
down_revision = 'd8f05ff5b716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_go', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('is_go')

    # ### end Alembic commands ###
