"""empty message

Revision ID: b04dc54f5599
Revises: 5bb42056eab7
Create Date: 2021-08-21 06:05:45.878069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b04dc54f5599'
down_revision = '5bb42056eab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_true', sa.Integer(), nullable=True))
        batch_op.drop_column('is_send')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_send', sa.INTEGER(), nullable=True))
        batch_op.drop_column('is_true')

    # ### end Alembic commands ###
