"""empty message

Revision ID: bb62f6e7c648
Revises: d6b890eadb10
Create Date: 2021-07-28 01:52:00.384219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb62f6e7c648'
down_revision = 'd6b890eadb10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_expectations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_pregnancy', sa.Boolean(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('date_request', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_expectations_date_request'), 'list_expectations', ['date_request'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_expectations_date_request'), table_name='list_expectations')
    op.drop_table('list_expectations')
    # ### end Alembic commands ###
