"""empty message

Revision ID: c26cc9a623ac
Revises: adea0c2471fe
Create Date: 2021-09-03 12:19:23.570966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26cc9a623ac'
down_revision = 'adea0c2471fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_full_name', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('diagnoz', sa.String(length=255), nullable=True),
    sa.Column('birthday', sa.String(length=255), nullable=True),
    sa.Column('osmotr', sa.String(length=255), nullable=True),
    sa.Column('end', sa.String(length=255), nullable=True),
    sa.Column('desc', sa.String(length=255), nullable=True),
    sa.Column('doctor_full_name', sa.String(length=255), nullable=True),
    sa.Column('apparate', sa.String(length=255), nullable=True),
    sa.Column('lp', sa.String(length=255), nullable=True),
    sa.Column('lp_full', sa.String(length=255), nullable=True),
    sa.Column('lp_index', sa.String(length=255), nullable=True),
    sa.Column('lzd', sa.String(length=255), nullable=True),
    sa.Column('lzs', sa.String(length=255), nullable=True),
    sa.Column('lzd_index', sa.String(length=255), nullable=True),
    sa.Column('vals', sa.String(length=255), nullable=True),
    sa.Column('sin', sa.String(length=255), nullable=True),
    sa.Column('vos', sa.String(length=255), nullable=True),
    sa.Column('duga', sa.String(length=255), nullable=True),
    sa.Column('kdo', sa.String(length=255), nullable=True),
    sa.Column('kso', sa.String(length=255), nullable=True),
    sa.Column('kdo_index', sa.String(length=255), nullable=True),
    sa.Column('pp', sa.String(length=255), nullable=True),
    sa.Column('pz', sa.String(length=255), nullable=True),
    sa.Column('npv', sa.String(length=255), nullable=True),
    sa.Column('mzp', sa.String(length=255), nullable=True),
    sa.Column('zs', sa.String(length=255), nullable=True),
    sa.Column('imm', sa.String(length=255), nullable=True),
    sa.Column('la', sa.String(length=255), nullable=True),
    sa.Column('la_mm', sa.String(length=255), nullable=True),
    sa.Column('fb', sa.String(length=255), nullable=True),
    sa.Column('fbt', sa.String(length=255), nullable=True),
    sa.Column('vmax', sa.String(length=255), nullable=True),
    sa.Column('pmax', sa.String(length=255), nullable=True),
    sa.Column('pmean', sa.String(length=255), nullable=True),
    sa.Column('ava', sa.String(length=255), nullable=True),
    sa.Column('regu', sa.String(length=255), nullable=True),
    sa.Column('vmaxMV', sa.String(length=255), nullable=True),
    sa.Column('pmaxMV', sa.String(length=255), nullable=True),
    sa.Column('pmeanMV', sa.String(length=255), nullable=True),
    sa.Column('mva', sa.String(length=255), nullable=True),
    sa.Column('regu2', sa.String(length=255), nullable=True),
    sa.Column('vmaxPV', sa.String(length=255), nullable=True),
    sa.Column('pmaxPV', sa.String(length=255), nullable=True),
    sa.Column('pmeanPV', sa.String(length=255), nullable=True),
    sa.Column('regu3', sa.String(length=255), nullable=True),
    sa.Column('vmaxTV', sa.String(length=255), nullable=True),
    sa.Column('pmaxTV', sa.String(length=255), nullable=True),
    sa.Column('pmeanTV', sa.String(length=255), nullable=True),
    sa.Column('regu4', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_results'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
