"""empty message

Revision ID: d6b890eadb10
Revises: 3ae1cbdcc06b
Create Date: 2021-07-26 16:17:00.848792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6b890eadb10'
down_revision = '3ae1cbdcc06b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schedule')
    op.add_column('records', sa.Column('comment', sa.String(length=255), nullable=True))
    op.drop_column('records', 'reason')
    op.drop_column('records', 'trust')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('trust', sa.BOOLEAN(), nullable=True))
    op.add_column('records', sa.Column('reason', sa.VARCHAR(length=255), nullable=True))
    op.drop_column('records', 'comment')
    op.create_table('schedule',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('doctor_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('date', sa.VARCHAR(length=255), nullable=True),
    sa.Column('time', sa.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', sa.VARCHAR(length=255), nullable=True),
    sa.Column('office', sa.VARCHAR(length=255), nullable=True),
    sa.Column('record_id', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
