"""empty message

Revision ID: d8f05ff5b716
Revises: 7afeb9f89de6
Create Date: 2021-08-23 02:46:42.645686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f05ff5b716'
down_revision = '7afeb9f89de6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_index('ix_records_is_interview')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.create_index('ix_records_is_interview', ['is_interview'], unique=False)

    # ### end Alembic commands ###
