"""empty message

Revision ID: e49cbb785ac6
Revises: 867a33637d3f
Create Date: 2021-07-21 20:59:32.466479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e49cbb785ac6'
down_revision = '867a33637d3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('personal', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('personal', 'is_active')
    # ### end Alembic commands ###
