"""empty message

Revision ID: f6e37cd2f0fb
Revises: 7b727214e956
Create Date: 2021-09-03 16:04:39.453480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6e37cd2f0fb'
down_revision = '7b727214e956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_docs_path', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('docs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_docs_path', ['path'])

    # ### end Alembic commands ###
