"""doctors table

Revision ID: f76337e8a5c8
Revises: f70b66612b06
Create Date: 2021-07-04 19:04:12.357694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f76337e8a5c8'
down_revision = 'f70b66612b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctors', sa.Column('login', sa.String(length=50), nullable=True))
    op.add_column('doctors', sa.Column('passwd', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('login', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('passwd', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passwd')
    op.drop_column('users', 'login')
    op.drop_column('doctors', 'passwd')
    op.drop_column('doctors', 'login')
    # ### end Alembic commands ###
